name: NuGet

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v3  
          
      - name: Build solution and generate NuGet package
        run: |  
          cd ./src/
          dotnet pack -c Release -o out -p:GeneratePackageOnBuild=false
        
      - name: Push Package to NuGet.org
        run: dotnet nuget push ./src/out/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
